theme: architect
title: Programming in Haskell
author: Francis Uldéric Girard
description: Learning Haskell - Languaage basic, Type system, Class Types, From functor to Monad, Parallelism for free
